### ISSUE TITLE
Any possiblity of rest operation?

### ISSUE THREAD

**Issue by AlseFum** [shuckster/match-iz#6]
You know there is a need to deal with pattern of uncertain length, like below
match([ "Hey it's the start" , 114514 , "left is some magic number. the rest are all numbers" , 1 , 42 , 24 , 21 , 42,...])
  (when([isString, 114514,isString, rest(isNumber)],(x)=>"Yay"),
  otherwise(_=>"I wish it could match but, ")
  )
I need it, please

BTW i like this libray :-P

**Comment by shuckster** [comment]
Hey, thanks for the suggestion. Glad to hear you like the library.

I have `rest` working for arrays locally, but the update will require a major version-bump since I'll have to drop this line:

https://github.com/shuckster/match-iz/blob/4564074e9245cc95557c395cddcf6adb92ce58e1/src/match-iz.mjs#L159

---

To migrate the matching of exact lengths of arrays, we'll need to change things like this:

```js
let maybeVariableLength = [1, 2, 3];
match(maybeVariableLength)(
  when([1, 2], 2),
  when([1, 2, 3], 3),
  otherwise(false),
);
// 3
```

To this:

```js
let maybeVariableLength = [1, 2, 3];
match(maybeVariableLength)(
  when(allOf({ length: 2 }, [[1, 2]]), 2),
  when(allOf({ length: 3 }, [[1, 2, 3]]), 3),
  otherwise(false),
);
// 3
```

To avoid the double `[[` `]]` syntax, we'd also have to drop the use of `.flat` in `allOf` and related helpers.

Perhaps I could update `eq` to work with arrays?

```js
let maybeVariableLength = [1, 2, 3];
match(maybeVariableLength)(
  when(eq([1, 2]), 2),
  when(eq([1, 2, 3]), 3),
  otherwise(false),
);
// 3
```

That might be the right thing to do, since it would make arrays consistent with how objects already work.

I'll have a play with it and see what makes sense.

**Comment by AlseFum** [comment]
glad to see.
Now I'm trying to use customized needle function to handle, regarding some precision. It works, though not so elegant.

**Comment by shuckster** [comment]
Interesting! Glad you found a workaround.

I think I've found a solution I'm happy with. It will look like this:

```js
// Objects
match(input)(
  when({ one: 1, ...rest(isNumber) }, (haystack, rest) => {
    // ...
  }),
)

// Arrays
match(input)(
  when([1, rest(isNumber)], (haystack, rest) => {
    // ...
  }),
)
```

You can omit the `rest` argument to capture everything:

```js
// Objects
match(input)(
  when({ one: 1, ...rest(isNumber) }, (haystack, rest) => {
    // ...
  }),
)

// Arrays
match(input)(
  when([1, rest()], (haystack, rest) => {
    // ...
  }),
)
```

So for arrays it's `rest()` and objects `...rest()`.

I have also tweaked `eq` as I mentioned above for strict array matching:

```js
match([1, 2, 3])(
  when(eq([1, 2]), 2),
  when(eq([1, 2, 3]), 3),
  otherwise(false),
);
// 3
```

I'm not sure exactly when the update will land. I need to update some failing tests off the back of the `eq` update, but there aren't very many.

I'm also not clear on how the TypeScript `.d.ts` file will need to change, but that needs a bit of attention anyway, and I'm not going to go too deep on it for this release.

Anyway, hopefully `v5` will be available in the next few days with `rest`.

**Comment by AlseFum** [comment]
looks nice bro, willing to see the update!

**Comment by shuckster** [comment]
I've pushed `rest` to the repo, but not published the new version to `npm` yet. Can you give it a try please? Just download one of the built files and use it directly to test:

- https://github.com/shuckster/match-iz/tree/37adc9642eb18ae897a2f13d78a81aeca36e49fe/dist

The CHANGELOG has the info I entered previously:

- https://github.com/shuckster/match-iz/blob/37adc9642eb18ae897a2f13d78a81aeca36e49fe/CHANGELOG.md#unreleased

**Comment by shuckster** [comment]
Update: Since `eq` was updated I needed to apply some fixes.

Here is the updated link to try this out:

- https://github.com/shuckster/match-iz/tree/3fe7637eb27481420def7031e379fb7721fb4e6b/dist

**Comment by AlseFum** [comment]
I simply ran the test and error occured. Below is console prints.

`Error: AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

9 !== 5


^
| Test case failed in [0]: inTheNext(...)`

Pity I'm occupied now. Maybe after several weeks I could come for more help.

**Comment by shuckster** [comment]
Looks like I was too late with my update! I posted a fix for that just above. 

Anyway, thanks for testing. Hopefully by the time you come back this will all be done.

**Comment by AlseFum** [comment]
> I simply ran the test and error occured. Below is console prints.
> 
> ```
> 
> 9 !== 5
> 
> 
> ^
> | Test case failed in [0]: inTheNext(...)
> ```
> 
> Pity I'm occupied now. Maybe after several weeks I could come for more help.

It seems not the new feature's vault.
In dates/utc/index.mjs, lines 116-119
The closure here uses "Date.now" as timestamp, and when I ran the test, it's approximately 2024/12/15. A little far away from 2024/12/12 written in test case.

**Comment by shuckster** [comment]
Thanks. Looks like that test needs mocking.

Actually, the whole suite could do with a refactor using a proper test runner. I'll do that before I publish a new version with `rest`, so let me know if `rest` works for you in the basic case.

**Comment by AlseFum** [comment]
It works fine in my case.
:-)

**Comment by shuckster** [comment]
Good to hear.

I seem to have found a fix for that failing test using the information you gave, but I have no idea why it works:

- https://github.com/shuckster/match-iz/blob/27eba9dc5ba9d631ea462e47b598a22003c27efa/dates/utc/index.mjs#L118-L119

At least I've broken the monolithic test-suite up, so it should be a bit easier to debug this kind of thing.

**Comment by shuckster** [comment]
`v5` published.
